In [8]:
import torch
from __future__ import print_function

# 基础

1、张量、张量对应的操作

2、张量和numpy相互转换

In [26]:
x = torch.empty(5, 3)

# Autograd 自动分化

## requires_grad 跟踪某个张量的所有操作

In [37]:
x = torch.ones(2, 2, requires_grad=True)

In [40]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [41]:
y.grad_fn

In [42]:
z = y * y * 3
out = z.mean()

In [45]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [53]:
out.requires_grad_(True)

tensor(27., grad_fn=<MeanBackward1>)

## Grad

In [55]:
out.backward()

In [56]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

梯度的解释：

1、一维 => 一阶倒数

2、多维 => 雅克比矩阵

In [57]:
x = torch.randn(3, requires_grad=True)

In [59]:
y = x * 2

In [64]:
while y.data.norm() < 1000:
    y = y * 2

此时y为矢量

In [69]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [71]:
y.backward(v)

In [72]:
x.grad

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])

# 神经网络

1、定义【可学习参数】

2、迭代输入数据集

3、网络处理输入

4、计算损失

5、将Grad传播回网络参数

6、通过简单的更新规则，更新权重

In [76]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
from 